In [38]:
from demoparser2 import DemoParser
from awpy import Demo

import pandas as pd
import numpy as np

demo_path = "./demos/natus-vincere-vs-vitality-m1-dust2.dem"

parser = DemoParser(demo_path)
awpy_parser = Demo(demo_path)

awpy_parser.parse()

In [39]:
event_names = parser.list_game_events()

df_all = parser.parse_events(["all"])

df_all

[('round_announce_match_start',
     tick
  0  1275),
 ('player_ping',
      entityid    tick  urgent  user_name       user_steamid            x  \
  0        357   22255   False      mezii  76561197973140692  2993.327637
  1        342   23976   False         iM  76561198050250233   287.695801
  2        151   31791   False    Aleksib  76561198013243326   160.122742
  3        151   31821    True    Aleksib  76561198013243326   160.122742
  4        151   31856   False    Aleksib  76561198013243326   193.621918
  5        409   33862   False      mezii  76561197973140692   848.219849
  6        348   40388   False        b1t  76561198246607476 -1920.000000
  7        348   40492   False        b1t  76561198246607476 -1921.477051
  8        348   40627   False        b1t  76561198246607476 -1920.000000
  9        348   40664   False        b1t  76561198246607476 -1920.000000
  10       360   40905   False      mezii  76561197973140692  1632.493896
  11       360   40914    True      mezii  76561197973140692  1634.472290
  12       414   43439   False      ZywOo  76561198113666193  -912.133423
  13       414   43663   False      ZywOo  76561198113666193  -905.484375
  14       500   45880   False  w0nderful  76561199063068840   277.943176
  15       410   45906   False         iM  76561198050250233   277.943176
  16       440   47668   False      mezii  76561197973140692   630.684387
  17       368   48713   False  w0nderful  76561199063068840 -1906.415527
  18       152   49685   False  w0nderful  76561199063068840  -364.248108
  19       136   50263   False         iM  76561198050250233  1309.261230
  20       157   54634   False    makazze  76561199076189612   182.249908
  21       507   59064   False       ropz  76561197991272318 -1925.270630
  22       205   60296   False       apEX  76561197989744167 -1841.591064
  23       107   66744   False  w0nderful  76561199063068840 -2201.071533
  24       136   83646   False       ropz  76561197991272318    -2.807236
  25        97   97049   False  w0nderful  76561199063068840  -533.000000
  26        97   97098   False  w0nderful  76561199063068840  -533.000000
  27        97   97171   False  w0nderful  76561199063068840   395.150879
  28       295  110475   False         iM  76561198050250233  1632.005615
  29       345  116433   False  w0nderful  76561199063068840  -700.424683
  30       367  135003   False      mezii  76561197973140692 -2048.000000
  31       362  138665   False         iM  76561198050250233 -1087.223022
  32       362  138685    True         iM  76561198050250233 -1083.369751
  33       140  139741   False      mezii  76561197973140692 -1941.749512
  34       441  140619   False      mezii  76561197973140692 -2003.255127
  35       229  145343   False      mezii  76561197973140692 -1660.310913
  36       158  146452   False    makazze  76561199076189612  1240.872314
  37        92  148340   False      mezii  76561197973140692   189.941711
  38       383  156591   False    makazze  76561199076189612 -1389.514404
  39       383  156745   False    makazze  76561199076189612 -1363.736328
  40       383  156764    True    makazze  76561199076189612 -1350.303223
  41       476  161102   False  w0nderful  76561199063068840  -804.065491
  42       416  168793   False  w0nderful  76561199063068840  -374.057312
  43       343  169638   False      mezii  76561197973140692 -2304.000000
  44       131  182955   False  w0nderful  76561199063068840  -391.331207
  45       356  185573   False        b1t  76561198246607476   768.000000
  46        75  187337   False       apEX  76561197989744167  1024.000488
  47        75  187353    True       apEX  76561197989744167  1024.043213
  48       342  189566   False         iM  76561198050250233  -846.380493
  49       357  194943   False      mezii  76561197973140692 -1344.000000

                y           z
  0  -1045.170898  -32.000000
  1   2059.167236  206.574051
  2   2369.676270  -83.918709
  3   2369.676270  -83.918709
  4   2225.784912 -125.124039
  5    264.000000  338.148163
  6   1458.006226   94.181465
  7   1435.668823   87.037537
  8   1491.619873   79.737732
  9   1588.049561   83.723030
  10   288.000122  100.748871
  11   288.000000  100.535599
  12  -885.831909  118.055817
  13  -872.883667  117.216270
  14  2273.775391 -124.001205
  15  2273.775391 -124.001205
  16   713.213806  378.913422
  17  1964.680664   92.625259
  18  2038.940674 -128.037521
  19  2008.289185   -1.166656
  20  2439.011719  -84.968750
  21  2647.962402   31.292076
  22  1883.901611    0.021458
  23  2215.842041   55.510025
  24  1989.981201 -102.725677
  25  -754.000000  149.848969
  26  -754.000000  149.848969
  27  -486.411591   42.547348
  28  2610.148193  119.272522
  29  2405.807373 -103.608002
  30  1640.203857  189.852356
  31  1327.941040 -112.098022
  32  1328.019775 -112.098526
  33  1792.038696  243.753464
  34  1792.020508  247.241318
  35  1280.000000   52.296604
  36  1216.001221   35.447701
  37  2552.220947  -47.027176
  38  -469.447174  128.045776
  39  -410.099304  128.133667
  40  -391.265472  128.185165
  41  2587.288574  -43.934799
  42  -640.188232  105.860138
  43  1559.440674  518.366516
  44  1652.392090  -68.946854
  45   492.192749    0.235245
  46  2393.779785   42.566696
  47  2391.734863   48.514427
  48  -813.199097  116.934311
  49  2500.369629  112.022156  ),
 ('decoy_started',
     entityid    tick user_name       user_steamid            x           y  \
  0        78  191592   Aleksib  76561198013243326  1336.723999  1290.42334

            z
  0 -7.106162  ),
 ('player_ping_stop',
      entityid    tick  user_name  user_steamid
  0        357   22639        NaN           NaN
  1        342   24360        NaN           NaN
  2        151   32240        NaN           NaN
  3        409   34246        NaN           NaN
  4        348   41048        NaN           NaN
  5        360   41298        NaN           NaN
  6        414   44047        NaN           NaN
  7        500   46264        NaN           NaN
  8        410   46290        NaN           NaN
  9        440   48052        NaN           NaN
  10       368   49097        NaN           NaN
  11       152   50069        NaN           NaN
  12       136   50647        NaN           NaN
  13       157   55018        NaN           NaN
  14       507   59448        NaN           NaN
  15       205   60680        NaN           NaN
  16       107   67128        NaN           NaN
  17        88   75039        NaN           NaN
  18       136   84030        NaN           NaN
  19        97   97555        NaN           NaN
  20       295  110859        NaN           NaN
  21       345  116817        NaN           NaN
  22       367  135387        NaN           NaN
  23       362  139069        NaN           NaN
  24       140  140125        NaN           NaN
  25       441  141003        NaN           NaN
  26       229  145727        NaN           NaN
  27       158  146836        NaN           NaN
  28        92  148724        NaN           NaN
  29       420  152277        NaN           NaN
  30       383  157148        NaN           NaN
  31       476  161486        NaN           NaN
  32       416  169177        NaN           NaN
  33       343  170022        NaN           NaN
  34       131  183339        NaN           NaN
  35       356  185957        NaN           NaN
  36        75  187737        NaN           NaN
  37       342  189950        NaN           NaN
  38       357  195327        NaN           NaN),
 ('player_hurt',
       armor attacker_name   attacker_steamid  dmg_armor  dmg_health  health  \
  0       90       Aleksib  76561198013243326         10          15      85
  1       91       Aleksib  76561198013243326          9          14      86
  2      100       Aleksib  76561198013243326          0           0     100
  3       94          apEX  76561197989744167          6          11      89
  4       94          apEX  76561197989744167          0          97       0
  ..     ...           ...                ...        ...         ...     ...
  643     93           b1t  76561198246607476          4          27      19
  644     93           b1t  76561198246607476          0          21       0
  645     83          ropz  76561197991272318          4          34       0
  646     63        flameZ  76561197978835160          1           5       7
  647     60          ropz  76561197991272318          3          21       0

        hitgroup    tick  user_name       user_steamid     weapon
  0      generic    2863      ZywOo  76561198113666193  hegrenade
  1      generic    2863     flameZ  76561197978835160  hegrenade
  2      generic    2863       ropz  76561197991272318  hegrenade
  3        chest    3129  w0nderful  76561199063068840      glock
  4         head    3139  w0nderful  76561199063068840      glock
  ..         ...     ...        ...                ...        ...
  643    stomach  195533      ZywOo  76561198113666193    galilar
  644  right_leg  195550      ZywOo  76561198113666193    galilar
  645    stomach  195994  w0nderful  76561199063068840       ak47
  646      chest  196138        b1t  76561198246607476       m4a1
  647  right_arm  196285        b1t  76561198246607476       ak47

  [648 rows x 11 columns]),
 ('fire_bullets',
        angles_x    angles_y      angles_z  attack_type  ent_origin_x  \
  0    -2.455210  -90.628372  0.000000e+00            0   -404.119049
  1    -1.577774  -90.417191  0.000000e+00            0   -403.317413
  2    -1.258025  -90.232407  0.000000e+00            0   -411.086304
  3    -1.484044  -90.285202  0.000000e+00            0   -407.504272
  4    -1.397738  -90.364395  0.000000e+00            0   -402.975800
  ...        ...         ...           ...          ...           ...
  2669 -5.884357  179.430481 -1.406786e-06            0   -335.860626
  2670 -5.536042  180.108734 -2.633390e-06            0   -338.515411
  2671  1.752265    0.723332  0.000000e+00            0  -1914.632935
  2672  2.415213   -0.171578 -6.211669e-06            0  -1914.757324
  2673  3.137285    0.218392 -7.214593e-10            0  -1914.752319

        ent_origin_y  ent_origin_z  inaccuracy  item_def_index  mode  ...  \
  0      2393.416992    -96.472328    0.003729              61     1  ...
  1      2393.411377    -96.457207    0.013326              61     1  ...
  2      2393.466309    -96.604439    0.014375              61     1  ...
  3      2393.449219    -96.534523    0.019450              61     1  ...
  4      2393.433350    -96.446075    0.020651              61     1  ...
  ...            ...           ...         ...             ...   ...  ...
  2669   2262.594482   -119.155899    0.016627              16     0  ...
  2670   2262.870605   -119.020523    0.016685              16     0  ...
  2671   2318.397461      0.140594    0.006410               7     0  ...
  2672   2318.323486      0.133422    0.010344               7     0  ...
  2673   2321.638184      0.257183    0.012937               7     0  ...

        recoil_index  round        seed  sound_dsp_effect  sound_type  spread  \
  0         0.000000      1  3603184605        1693280391           9  0.0015
  1         0.749894      1  2974627030        1693280391           9  0.0015
  2         1.136349      1  4275552977        1693280391           9  0.0015
  3         1.721560      1  1389276285        1693280391           9  0.0015
  4         2.356774      1   419669088        1693280391           9  0.0015
  ...            ...    ...         ...               ...         ...     ...
  2669      8.000000     24  2181169263        1693280391           2  0.0006
  2670      9.000000     24  1209716994        1693280391           2  0.0006
  2671      0.000000     24   257606960        2005810340           2  0.0006
  2672      1.000000     24  2506950215        2005810340           2  0.0006
  2673      2.000000     25  3989729011        2005810340           2  0.0006

          tick  user_name       user_steamid  weapon_id
  0       1874         iM  76561198050250233    7127547
  1       1890         iM  76561198050250233    7127547
  2       1908         iM  76561198050250233    7127547
  3       1922         iM  76561198050250233    7127547
  4       1936         iM  76561198050250233    7127547
  ...      ...        ...                ...        ...
  2669  196167     flameZ  76561197978835160    6389859
  2670  196173     flameZ  76561197978835160    6389859
  2671  196272       ropz  76561197991272318   10682759
  2672  196278       ropz  76561197991272318   10682759
  2673  196285       ropz  76561197991272318   10682759

  [2674 rows x 27 columns]),
 ('flashbang_detonate',
       entityid    tick  user_name       user_steamid            x            y  \
  0         415    2973      mezii  76561197973140692   680.213562  2336.711914
  1         300    3198      mezii  76561197973140692  1008.079102  2815.074707
  2         345    4706    Aleksib  76561198013243326   713.475830  2087.206055
  3         164    7383    Aleksib  76561198013243326  1074.294067  1193.300049
  4         161   12908    Aleksib  76561198013243326  1362.192383  1296.815918
  ..        ...     ...        ...                ...          ...          ...
  178        89  194822  w0nderful  76561199063068840 -1430.442627  2620.491211
  179       101  195823     flameZ  76561197978835160  -263.858917  2226.735596
  180       180  195944     flameZ  76561197978835160  -343.843170  2263.417969
  181       113  196028     flameZ  76561197978835160  -385.063141  2232.106934
  182       368  196224       ropz  76561197991272318 -2315.677979  2223.668945

                z
  0    726.803345
  1    266.420898
  2    704.483215
  3    407.555725
  4    465.550293
  ..          ...
  178  262.028137
  179  -97.942711
  180 -111.034554
  181  -92.882568
  182  642.941040

  [183 rows x 7 columns]),
 ('bomb_pickup',
        tick  user_name       user_steamid
  0     5594     flameZ  76561197978835160
  1     5683       ropz  76561197991272318
  2     5928      mezii  76561197973140692
  3     7172      ZywOo  76561198113666193
  4     7468       apEX  76561197989744167
  ..     ...        ...                ...
  70  188643         iM  76561198050250233
  71  189084    makazze  76561199076189612
  72  189337         iM  76561198050250233
  73  190682    Aleksib  76561198013243326
  74  191849  w0nderful  76561199063068840

  [75 rows x 3 columns]),
 ('player_death',
       assistedflash assister_name   assister_steamid attacker_name  \
  0            False           NaN                NaN          apEX
  1            False           b1t  76561198246607476       makazze
  2            False           NaN                NaN           b1t
  3            False          ropz  76561197991272318        flameZ
  4            False           NaN                NaN         mezii
  ..             ...           ...                ...           ...
  140          False       makazze  76561199076189612           b1t
  141          False           NaN                NaN     w0nderful
  142          False     w0nderful  76561199063068840           b1t
  143          False          apEX  76561197989744167          ropz
  144          False         mezii  76561197973140692          ropz

        attacker_steamid  attackerblind  attackerinair   distance  dmg_armor  \
  0    76561197989744167          False          False  16.326532          0
  1    76561199076189612          False          False  22.113338          0
  2    76561198246607476          False          False   5.570378          0
  3    76561197978835160          False          False  20.425627          0
  4    76561197973140692          False          False  18.260557          0
  ..                 ...            ...            ...        ...        ...
  140  76561198246607476          False          False  14.103883          3
  141  76561199063068840          False          False  17.916819          5
  142  76561198246607476          False          False  29.827475          0
  143  76561197991272318          False          False  14.338522          4
  144  76561197991272318          False          False   9.084195          3

       dmg_health  ...  revenge  thrusmoke    tick  user_name  \
  0            97  ...        0      False    3139  w0nderful
  1            29  ...        0      False    3533       apEX
  2           134  ...        0      False    4797       ropz
  3            92  ...        0      False    4835        b1t
  4            20  ...        0      False    5112    Aleksib
  ..          ...  ...      ...        ...     ...        ...
  140          22  ...        0      False  195106      mezii
  141         442  ...        0      False  195178       apEX
  142          21  ...        0       True  195550      ZywOo
  143          34  ...        0      False  195994  w0nderful
  144          21  ...        0      False  196285        b1t

            user_steamid        weapon     weapon_fauxitemid  weapon_itemid  \
  0    76561199063068840         glock  17293822569165815812    22270099526
  1    76561197989744167  usp_silencer  17293822569135734845    47759803756
  2    76561197991272318  usp_silencer  17293822569135734845    48886811137
  3    76561198246607476         glock  17293822569105850372    34768596195
  4    76561198013243326         glock  17293822569125838852    48204352433
  ..                 ...           ...                   ...            ...
  140  76561197973140692       galilar  17293822569128787981    27606258955
  141  76561197989744167           awp  17293822569152249865    51214955132
  142  76561198113666193       galilar  17293822569128787981    27606258955
  143  76561199063068840          ak47  17293822569114501127    41782428693
  144  76561198246607476          ak47  17293822569114501127    41782428693

       weapon_originalowner_xuid wipe
  0                                 0
  1                                 0
  2                                 0
  3                                 0
  4                                 0
  ..                         ...  ...
  140                               0
  141                               0
  142                               0
  143                               0
  144                               0

  [145 rows x 26 columns]),
 ('round_start',
      round    tick
  0       1       1
  1       2    5594
  2       3   11139
  3       4   14926
  4       5   17869
  5       6   21173
  6       7   30133
  7       8   42760
  8       9   54161
  9      10   61863
  10     11   69642
  11     12   76734
  12     13   82064
  13     14  103016
  14     15  111560
  15     16  121075
  16     17  128597
  17     18  136356
  18     19  143059
  19     20  148306
  20     21  155259
  21     22  165221
  22     23  177463
  23     24  188366),
 ('item_pickup',
        defindex          item  silent    tick  user_name       user_steamid
  0           50          vest   False      19  w0nderful  76561199063068840
  1           50          vest   False      63        b1t  76561198246607476
  2           50          vest   False      71    makazze  76561199076189612
  3           50          vest   False      74       ropz  76561197991272318
  4           45  smokegrenade   False     120       apEX  76561197989744167
  ...        ...           ...     ...     ...        ...                ...
  1576        13       galilar   False  195016        b1t  76561198246607476
  1577         7          ak47    True  195033      mezii  76561197973140692
  1578        43     flashbang   False  195631     flameZ  76561197978835160
  1579        43     flashbang   False  195635     flameZ  76561197978835160
  1580        43     flashbang   False  195742     flameZ  76561197978835160

  [1581 rows x 6 columns]),
 ('cs_round_final_beep',
        tick
  0     1275
  1     6874
  2    12419
  3    16206
  4    19149

In [40]:
df_deaths = parser.parse_event("player_death")

df_deaths

,assistedflash,assister_name,assister_steamid,attacker_name,attacker_steamid,attackerblind,attackerinair,distance,dmg_armor,dmg_health,...,revenge,thrusmoke,tick,user_name,user_steamid,weapon,weapon_fauxitemid,weapon_itemid,weapon_originalowner_xuid,wipe
0,False,NaN,NaN,apEX,76561197989744167,False,False,16.326532,0,97,...,0,False,3139,w0nderful,76561199063068840,glock,17293822569165815812,22270099526,,0
1,False,b1t,76561198246607476,makazze,76561199076189612,False,False,22.113338,0,29,...,0,False,3533,apEX,76561197989744167,usp_silencer,17293822569135734845,47759803756,,0
2,False,NaN,NaN,b1t,76561198246607476,False,False,5.570378,0,134,...,0,False,4797,ropz,76561197991272318,usp_silencer,17293822569135734845,48886811137,,0
3,False,ropz,76561197991272318,flameZ,76561197978835160,False,False,20.425627,0,92,...,0,False,4835,b1t,76561198246607476,glock,17293822569105850372,34768596195,,0
4,False,NaN,NaN,mezii,76561197973140692,False,False,18.260557,0,20,...,0,False,5112,Aleksib,76561198013243326,glock,17293822569125838852,48204352433,,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,False,makazze,76561199076189612,b1t,76561198246607476,False,False,14.103883,3,22,...,0,False,195106,mezii,76561197973140692,galilar,17293822569128787981,27606258955,,0
141,False,NaN,NaN,w0nderful,76561199063068840,False,False,17.916819,5,442,...,0,False,195178,apEX,76561197989744167,awp,17293822569152249865,51214955132,,0
142,False,w0nderful,76561199063068840,b1t,76561198246607476,False,False,29.827475,0,21,...,0,True,195550,ZywOo,76561198113666193,galilar,17293822569128787981,27606258955,,0
143,False,apEX,76561197989744167,ropz,76561197991272318,False,False,14.338522,4,34,...,0,False,195994,w0nderful,76561199063068840,ak47,17293822569114501127,41782428693,,0
144,False,mezii,76561197973140692,ropz,76561197991272318,False,False,9.084195,3,21,...,0,False,196285,b1t,76561198246607476,ak47,17293822569114501127,41782428693,,0

In [41]:
df_deaths.loc[df_deaths["assister_name"] == "w0nderful"]

,assistedflash,assister_name,assister_steamid,attacker_name,attacker_steamid,attackerblind,attackerinair,distance,dmg_armor,dmg_health,...,revenge,thrusmoke,tick,user_name,user_steamid,weapon,weapon_fauxitemid,weapon_itemid,weapon_originalowner_xuid,wipe
20,False,w0nderful,76561199063068840,makazze,76561199076189612,False,False,16.294065,0,35,...,0,False,17412,ropz,76561197991272318,ak47,17293822569196093447,51677688409,,0
21,False,w0nderful,76561199063068840,makazze,76561199076189612,False,False,14.510094,0,18,...,0,False,17515,mezii,76561197973140692,ak47,17293822569196093447,51677688409,,0
23,True,w0nderful,76561199063068840,Aleksib,76561198013243326,False,False,13.533549,0,5,...,0,False,19780,apEX,76561197989744167,inferno,,,,0
48,True,w0nderful,76561199063068840,Aleksib,76561198013243326,False,False,6.534457,11,52,...,0,False,68855,ropz,76561197991272318,m4a1_silencer,17293822569167192124,41782352566,,0
82,False,w0nderful,76561199063068840,iM,76561198050250233,False,False,25.756643,4,33,...,0,False,117154,ropz,76561197991272318,ak47,17293822569121185799,48004746928,,0
88,False,w0nderful,76561199063068840,b1t,76561198246607476,False,False,20.935261,0,139,...,0,True,126388,apEX,76561197989744167,ak47,17293822569121185799,48004746928,,0
105,False,w0nderful,76561199063068840,iM,76561198050250233,False,False,51.104286,1,107,...,0,True,147015,flameZ,76561197978835160,awp,17293822569152249865,51214955132,,0
142,False,w0nderful,76561199063068840,b1t,76561198246607476,False,False,29.827475,0,21,...,0,True,195550,ZywOo,76561198113666193,galilar,17293822569128787981,27606258955,,0

In [45]:
# awpy_parser.header
awpy_parser.kills

shape: (145, 47)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬──────┬───────────┐
│ assistedfl ┆ assister_X ┆ assister_Y ┆ assister_Z ┆ … ┆ weapon_it ┆ weapon_or ┆ wipe ┆ round_num │
│ ash        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ emid      ┆ iginalown ┆ ---  ┆ ---       │
│ ---        ┆ f32        ┆ f32        ┆ f32        ┆   ┆ ---       ┆ er_xuid   ┆ i32  ┆ u32       │
│ bool       ┆            ┆            ┆            ┆   ┆ str       ┆ ---       ┆      ┆           │
│            ┆            ┆            ┆            ┆   ┆           ┆ str       ┆      ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪══════╪═══════════╡
│ false      ┆ null       ┆ null       ┆ null       ┆ … ┆ 222700995 ┆           ┆ 0    ┆ 1         │
│            ┆            ┆            ┆            ┆   ┆ 26        ┆           ┆      ┆           │
│ false      ┆ -529.57330 ┆ 1441.27343 ┆ -111.39563 ┆ … ┆ 477598037 ┆           ┆ 0    ┆ 1         │
│            ┆ 3          ┆ 8          ┆            ┆   ┆ 56        ┆           ┆      ┆           │
│ false      ┆ null       ┆ null       ┆ null       ┆ … ┆ 488868111 ┆           ┆ 0    ┆ 1         │
│            ┆            ┆            ┆            ┆   ┆ 37        ┆           ┆      ┆           │
│ false      ┆ 565.637207 ┆ 2379.52172 ┆ 67.03125   ┆ … ┆ 347685961 ┆           ┆ 0    ┆ 1         │
│            ┆            ┆ 9          ┆            ┆   ┆ 95        ┆           ┆      ┆           │
│ false      ┆ null       ┆ null       ┆ null       ┆ … ┆ 482043524 ┆           ┆ 0    ┆ 1         │
│            ┆            ┆            ┆            ┆   ┆ 33        ┆           ┆      ┆           │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …    ┆ …         │
│ false      ┆ -1268.0587 ┆ 2661.36718 ┆ 130.03125  ┆ … ┆ 276062589 ┆           ┆ 0    ┆ 24        │
│            ┆ 16         ┆ 8          ┆            ┆   ┆ 55        ┆           ┆      ┆           │
│ false      ┆ null       ┆ null       ┆ null       ┆ … ┆ 512149551 ┆           ┆ 0    ┆ 24        │
│            ┆            ┆            ┆            ┆   ┆ 32        ┆           ┆      ┆           │
│ false      ┆ -1265.1807 ┆ 2255.90454 ┆ 4.465133   ┆ … ┆ 276062589 ┆           ┆ 0    ┆ 24        │
│            ┆ 86         ┆ 1          ┆            ┆   ┆ 55        ┆           ┆      ┆           │
│ false      ┆ -1699.8048 ┆ 1816.21923 ┆ 2.538283   ┆ … ┆ 417824286 ┆           ┆ 0    ┆ 24        │
│            ┆ 1          ┆ 8          ┆            ┆   ┆ 93        ┆           ┆      ┆           │
│ false      ┆ -1376.8917 ┆ 2695.99975 ┆ 125.03125  ┆ … ┆ 417824286 ┆           ┆ 0    ┆ 24        │
│            ┆ 24         ┆ 6          ┆            ┆   ┆ 93        ┆           ┆      ┆           │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴──────┴───────────┘

In [ ]:
# Let's make a simple scoreboard using data from the demo.
# It'll have the basic stuff: Kills, assists, deaths, ADR

from typing import List

class Scoreboard_Basic(object):

    def __init__(self, team_1_name: str, team_2_name: str, team_1_players: List[str], team_2_players: List[str], demo_path: str) -> None:
        """Initialize the Scoreboard_Basic object.

        :param team_1_name: the name of one of the teams that played this map
        :param team_2_name: the name of the other team that played this map
        :param team_1_players: a list of the players on Team 1
        :param team_2_players: a list of the players on Team 2
        :param demo_path: the path to the .dem file containing all of the replay gameplay data for this map
        :return: nothing

        """
        self.team_1_name = team_1_name
        self.team_2_name = team_2_name
        self.team_1_players = team_1_players
        self.team_2_players = team_2_players
        self.demo_path = demo_path

        # The DataFrame will be split such that each row contains the data for one player in the map
        #
        # The columns will be:
        #
        # team = the team a player is on
        # player = a player's official tag
        # kills = num of total kills from the player in the map
        # assists = num of total assists from the player in the map
        # deaths = num of total deaths from the player in the map
        # adr = the ADR of the player in the map (Average Damage per Round)

        self.scoreboard_cols = ["team", "player", "kills", "assists", "deaths", "adr"]
        self.scoreboard = pd.DataFrame(columns=self.scoreboard_cols)

    def create_scoreboard(self) -> None:
        """Create the scoreboard DataFrame.

        Access by using .scoreboard
        """

        pass